name: test

on:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
      - __tests__/src/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**
      - __tests__/src/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update npm
        run: npm install -g npm

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run coverage
